name: Golang Component CI

on:
  push:
    branches:
      - main

env:
  GO_VERSION: '1.22'
  GOLANG_LINTER_VERSION: v1.57

jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Go runtime
        uses: actions/setup-go@v5
        with:
          go-version: '$GO_VERSION'
      - name: Lint Code
        uses: golangci/golangci-lint-action@v5
        with:
          version: $GOLANG_LINTER_VERSION
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Go runtime
        uses: actions/setup-go@v5
        with:
          go-version: '$GO_VERSION'
      - name: Run Tests
        run: |
          go test



