name: Golang Component CI

on:
  push:
    branches:
      - main
    paths:
      - 'go_component/**'
      - '.github/workflows/Go-CI.yaml'

env:
  GO_VERSION: '1.22'
  GO_COMPONENT_PATH: go_component
  DOCKER_HUB_REPO: sonukiwi/inc42-assignment-go-app-repo

jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source-code
        uses: actions/checkout@v4
      - name: Install Go runtime
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Lint Code
        working-directory: ${{ env.GO_COMPONENT_PATH }}
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.0
          golangci-lint run
      - name: Upload source-code
        uses: actions/upload-artifact@v4
        with:
          name: source-code
          path: .
  Test:
    needs: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Download source-code
        uses: actions/download-artifact@v4
        with:
          name: source-code
      - name: Install Go runtime
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run Tests
        working-directory: ${{ env.GO_COMPONENT_PATH }}
        run: |
          go test
  BuildAndPush:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Download source-code
        uses: actions/download-artifact@v4
        with:
          name: source-code
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log In to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Get Short Git Commit Hash
        id: git_commit_hash
        run: |
          echo "::set-output name=short_hash::$(git rev-parse --short HEAD)"
      - name: Build Docker Image
        working-directory: ${{ env.GO_COMPONENT_PATH }}
        run: |
          TAG="${{ env.DOCKER_HUB_REPO }}:${{ steps.git_commit_hash.outputs.short_hash }}"
          docker build -t $TAG .
      - name: Push Docker Image
        run: |
          TAG="${{ env.DOCKER_HUB_REPO }}:${{ steps.git_commit_hash.outputs.short_hash }}"
          docker push $TAG





