name: Golang Component CI

on:
  push:
    branches:
      - main

env:
  GO_VERSION: '1.22'
  GOLANG_LINTER_VERSION: v1.57
  GO_COMPONENT_PATH: go_component

jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Go runtime
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Lint Code
        working-directory: ${{ env.GO_COMPONENT_PATH }}
        uses: golangci/golangci-lint-action@v5
        with:
          version: ${{ env.GOLANG_LINTER_VERSION }}
  Test:
    needs: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Go runtime
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run Tests
        working-directory: ${{ env.GO_COMPONENT_PATH }}
        run: |
          go test



