name: Golang Component CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Go runtime
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Lint Code
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.0
          golangci-lint run
      - name: Run Tests
        run: |
          go test



